# Generated by Django 5.2.3 on 2025-07-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_remove_customer_user_alter_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
